# Generated by Django 5.2.6 on 2025-09-25 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FraudPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fraud_type', models.CharField(max_length=50)),
                ('input_data', models.JSONField()),
                ('transaction_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('merchant_name', models.CharField(blank=True, max_length=100, null=True)),
                ('captured_text', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=False)),
                ('random_forest', models.BooleanField(blank=True, null=True)),
                ('random_forest_probability', models.FloatField(blank=True, null=True)),
                ('log_reg', models.BooleanField(blank=True, null=True)),
                ('log_reg_probability', models.FloatField(blank=True, null=True)),
                ('xgboost', models.BooleanField(blank=True, null=True)),
                ('xgboost_probability', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'fraud_predictions_new',
            },
        ),
    ]
